baseurl = "https://www.matteorosina.it/"
title = "Matteo Rosina"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Matteo Rosina"
  info = "SAP Developer, Flutter & Web3 passionate and Trail Runner"
  description = "Matteo Rosina's personal website"
  keywords = "sap,developer,runner,personal"
  avatarurl = "images/avatar.jpg"

  #faviconSVG = "/img/favicon.svg"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

# Social links
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/matteo-rosina-307606143/"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/matteorosina/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/matteo_rosina/"
[[params.social]]
  name = "E-Mail"
  icon = "fa-free fa-at fa-2x"
  weight = 4
  url = "mailto:matteo.rosina@gmail.com"
[[params.social]]
  name = "Strava"
  icon = "fa-brands fa-strava fa-2x"
  weight = 5
  url = "https://www.strava.com/athletes/matteo_rosina"

# Menu links
[[menu.main]]
  name = "Projects"
  weight = 1
  url  = "projects/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"